// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package crypt

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockDecryptor creates a new instance of MockDecryptor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDecryptor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDecryptor {
	mock := &MockDecryptor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDecryptor is an autogenerated mock type for the Decryptor type
type MockDecryptor struct {
	mock.Mock
}

type MockDecryptor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDecryptor) EXPECT() *MockDecryptor_Expecter {
	return &MockDecryptor_Expecter{mock: &_m.Mock}
}

// Decrypt provides a mock function for the type MockDecryptor
func (_mock *MockDecryptor) Decrypt(payload []byte) ([]byte, error) {
	ret := _mock.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for Decrypt")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) ([]byte, error)); ok {
		return returnFunc(payload)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = returnFunc(payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(payload)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDecryptor_Decrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decrypt'
type MockDecryptor_Decrypt_Call struct {
	*mock.Call
}

// Decrypt is a helper method to define mock.On call
//   - payload []byte
func (_e *MockDecryptor_Expecter) Decrypt(payload interface{}) *MockDecryptor_Decrypt_Call {
	return &MockDecryptor_Decrypt_Call{Call: _e.mock.On("Decrypt", payload)}
}

func (_c *MockDecryptor_Decrypt_Call) Run(run func(payload []byte)) *MockDecryptor_Decrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDecryptor_Decrypt_Call) Return(bytes []byte, err error) *MockDecryptor_Decrypt_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockDecryptor_Decrypt_Call) RunAndReturn(run func(payload []byte) ([]byte, error)) *MockDecryptor_Decrypt_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEncryptor creates a new instance of MockEncryptor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEncryptor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEncryptor {
	mock := &MockEncryptor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEncryptor is an autogenerated mock type for the Encryptor type
type MockEncryptor struct {
	mock.Mock
}

type MockEncryptor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEncryptor) EXPECT() *MockEncryptor_Expecter {
	return &MockEncryptor_Expecter{mock: &_m.Mock}
}

// Encrypt provides a mock function for the type MockEncryptor
func (_mock *MockEncryptor) Encrypt(plain []byte) ([]byte, error) {
	ret := _mock.Called(plain)

	if len(ret) == 0 {
		panic("no return value specified for Encrypt")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) ([]byte, error)); ok {
		return returnFunc(plain)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = returnFunc(plain)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(plain)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEncryptor_Encrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encrypt'
type MockEncryptor_Encrypt_Call struct {
	*mock.Call
}

// Encrypt is a helper method to define mock.On call
//   - plain []byte
func (_e *MockEncryptor_Expecter) Encrypt(plain interface{}) *MockEncryptor_Encrypt_Call {
	return &MockEncryptor_Encrypt_Call{Call: _e.mock.On("Encrypt", plain)}
}

func (_c *MockEncryptor_Encrypt_Call) Run(run func(plain []byte)) *MockEncryptor_Encrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEncryptor_Encrypt_Call) Return(bytes []byte, err error) *MockEncryptor_Encrypt_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockEncryptor_Encrypt_Call) RunAndReturn(run func(plain []byte) ([]byte, error)) *MockEncryptor_Encrypt_Call {
	_c.Call.Return(run)
	return _c
}
