// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package compress

import (
	mock "github.com/stretchr/testify/mock"
)

// newMockreader creates a new instance of mockreader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockreader(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockreader {
	mock := &mockreader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockreader is an autogenerated mock type for the reader type
type mockreader struct {
	mock.Mock
}

type mockreader_Expecter struct {
	mock *mock.Mock
}

func (_m *mockreader) EXPECT() *mockreader_Expecter {
	return &mockreader_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type mockreader
func (_mock *mockreader) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockreader_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type mockreader_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *mockreader_Expecter) Close() *mockreader_Close_Call {
	return &mockreader_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *mockreader_Close_Call) Run(run func()) *mockreader_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockreader_Close_Call) Return(err error) *mockreader_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockreader_Close_Call) RunAndReturn(run func() error) *mockreader_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function for the type mockreader
func (_mock *mockreader) Read(p []byte) (int, error) {
	ret := _mock.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return returnFunc(p)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = returnFunc(p)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockreader_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type mockreader_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - p []byte
func (_e *mockreader_Expecter) Read(p interface{}) *mockreader_Read_Call {
	return &mockreader_Read_Call{Call: _e.mock.On("Read", p)}
}

func (_c *mockreader_Read_Call) Run(run func(p []byte)) *mockreader_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockreader_Read_Call) Return(n int, err error) *mockreader_Read_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *mockreader_Read_Call) RunAndReturn(run func(p []byte) (int, error)) *mockreader_Read_Call {
	_c.Call.Return(run)
	return _c
}

// newMockwriter creates a new instance of mockwriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockwriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockwriter {
	mock := &mockwriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockwriter is an autogenerated mock type for the writer type
type mockwriter struct {
	mock.Mock
}

type mockwriter_Expecter struct {
	mock *mock.Mock
}

func (_m *mockwriter) EXPECT() *mockwriter_Expecter {
	return &mockwriter_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type mockwriter
func (_mock *mockwriter) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockwriter_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type mockwriter_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *mockwriter_Expecter) Close() *mockwriter_Close_Call {
	return &mockwriter_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *mockwriter_Close_Call) Run(run func()) *mockwriter_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockwriter_Close_Call) Return(err error) *mockwriter_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockwriter_Close_Call) RunAndReturn(run func() error) *mockwriter_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function for the type mockwriter
func (_mock *mockwriter) Write(p []byte) (int, error) {
	ret := _mock.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return returnFunc(p)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = returnFunc(p)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockwriter_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type mockwriter_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - p []byte
func (_e *mockwriter_Expecter) Write(p interface{}) *mockwriter_Write_Call {
	return &mockwriter_Write_Call{Call: _e.mock.On("Write", p)}
}

func (_c *mockwriter_Write_Call) Run(run func(p []byte)) *mockwriter_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockwriter_Write_Call) Return(n int, err error) *mockwriter_Write_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *mockwriter_Write_Call) RunAndReturn(run func(p []byte) (int, error)) *mockwriter_Write_Call {
	_c.Call.Return(run)
	return _c
}
