#!/bin/sh

command -v goimports >/dev/null 2>&1 || {
  echo "goimports not found"
  exit 1
}

GO_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep '\.go$')

if [ -n "$GO_FILES" ]; then
  echo "Running goimports on staged Go files..."
  for file in $GO_FILES; do
    goimports -w "$file"
    git add "$file"
  done
  echo "goimports completed."
fi
