// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"

	"github.com/gabkaclassic/metrics/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMetricsRepository creates a new instance of MockMetricsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetricsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetricsRepository {
	mock := &MockMetricsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMetricsRepository is an autogenerated mock type for the MetricsRepository type
type MockMetricsRepository struct {
	mock.Mock
}

type MockMetricsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetricsRepository) EXPECT() *MockMetricsRepository_Expecter {
	return &MockMetricsRepository_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type MockMetricsRepository
func (_mock *MockMetricsRepository) Add(context1 context.Context, metrics models.Metrics) error {
	ret := _mock.Called(context1, metrics)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Metrics) error); ok {
		r0 = returnFunc(context1, metrics)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMetricsRepository_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockMetricsRepository_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - context1 context.Context
//   - metrics models.Metrics
func (_e *MockMetricsRepository_Expecter) Add(context1 interface{}, metrics interface{}) *MockMetricsRepository_Add_Call {
	return &MockMetricsRepository_Add_Call{Call: _e.mock.On("Add", context1, metrics)}
}

func (_c *MockMetricsRepository_Add_Call) Run(run func(context1 context.Context, metrics models.Metrics)) *MockMetricsRepository_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Metrics
		if args[1] != nil {
			arg1 = args[1].(models.Metrics)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetricsRepository_Add_Call) Return(err error) *MockMetricsRepository_Add_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMetricsRepository_Add_Call) RunAndReturn(run func(context1 context.Context, metrics models.Metrics) error) *MockMetricsRepository_Add_Call {
	_c.Call.Return(run)
	return _c
}

// AddAll provides a mock function for the type MockMetricsRepository
func (_mock *MockMetricsRepository) AddAll(context1 context.Context, metricss []models.Metrics) error {
	ret := _mock.Called(context1, metricss)

	if len(ret) == 0 {
		panic("no return value specified for AddAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []models.Metrics) error); ok {
		r0 = returnFunc(context1, metricss)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMetricsRepository_AddAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddAll'
type MockMetricsRepository_AddAll_Call struct {
	*mock.Call
}

// AddAll is a helper method to define mock.On call
//   - context1 context.Context
//   - metricss []models.Metrics
func (_e *MockMetricsRepository_Expecter) AddAll(context1 interface{}, metricss interface{}) *MockMetricsRepository_AddAll_Call {
	return &MockMetricsRepository_AddAll_Call{Call: _e.mock.On("AddAll", context1, metricss)}
}

func (_c *MockMetricsRepository_AddAll_Call) Run(run func(context1 context.Context, metricss []models.Metrics)) *MockMetricsRepository_AddAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []models.Metrics
		if args[1] != nil {
			arg1 = args[1].([]models.Metrics)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetricsRepository_AddAll_Call) Return(err error) *MockMetricsRepository_AddAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMetricsRepository_AddAll_Call) RunAndReturn(run func(context1 context.Context, metricss []models.Metrics) error) *MockMetricsRepository_AddAll_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockMetricsRepository
func (_mock *MockMetricsRepository) Get(context1 context.Context, s string) (*models.Metrics, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *models.Metrics
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.Metrics, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.Metrics); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Metrics)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetricsRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockMetricsRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockMetricsRepository_Expecter) Get(context1 interface{}, s interface{}) *MockMetricsRepository_Get_Call {
	return &MockMetricsRepository_Get_Call{Call: _e.mock.On("Get", context1, s)}
}

func (_c *MockMetricsRepository_Get_Call) Run(run func(context1 context.Context, s string)) *MockMetricsRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetricsRepository_Get_Call) Return(metrics *models.Metrics, err error) *MockMetricsRepository_Get_Call {
	_c.Call.Return(metrics, err)
	return _c
}

func (_c *MockMetricsRepository_Get_Call) RunAndReturn(run func(context1 context.Context, s string) (*models.Metrics, error)) *MockMetricsRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockMetricsRepository
func (_mock *MockMetricsRepository) GetAll(context1 context.Context) (map[string]any, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 map[string]any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (map[string]any, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) map[string]any); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetricsRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockMetricsRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockMetricsRepository_Expecter) GetAll(context1 interface{}) *MockMetricsRepository_GetAll_Call {
	return &MockMetricsRepository_GetAll_Call{Call: _e.mock.On("GetAll", context1)}
}

func (_c *MockMetricsRepository_GetAll_Call) Run(run func(context1 context.Context)) *MockMetricsRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetricsRepository_GetAll_Call) Return(stringToV map[string]any, err error) *MockMetricsRepository_GetAll_Call {
	_c.Call.Return(stringToV, err)
	return _c
}

func (_c *MockMetricsRepository_GetAll_Call) RunAndReturn(run func(context1 context.Context) (map[string]any, error)) *MockMetricsRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllMetrics provides a mock function for the type MockMetricsRepository
func (_mock *MockMetricsRepository) GetAllMetrics(context1 context.Context) ([]models.Metrics, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for GetAllMetrics")
	}

	var r0 []models.Metrics
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]models.Metrics, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []models.Metrics); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Metrics)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetricsRepository_GetAllMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllMetrics'
type MockMetricsRepository_GetAllMetrics_Call struct {
	*mock.Call
}

// GetAllMetrics is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockMetricsRepository_Expecter) GetAllMetrics(context1 interface{}) *MockMetricsRepository_GetAllMetrics_Call {
	return &MockMetricsRepository_GetAllMetrics_Call{Call: _e.mock.On("GetAllMetrics", context1)}
}

func (_c *MockMetricsRepository_GetAllMetrics_Call) Run(run func(context1 context.Context)) *MockMetricsRepository_GetAllMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetricsRepository_GetAllMetrics_Call) Return(metricss []models.Metrics, err error) *MockMetricsRepository_GetAllMetrics_Call {
	_c.Call.Return(metricss, err)
	return _c
}

func (_c *MockMetricsRepository_GetAllMetrics_Call) RunAndReturn(run func(context1 context.Context) ([]models.Metrics, error)) *MockMetricsRepository_GetAllMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// Reset provides a mock function for the type MockMetricsRepository
func (_mock *MockMetricsRepository) Reset(context1 context.Context, metrics models.Metrics) error {
	ret := _mock.Called(context1, metrics)

	if len(ret) == 0 {
		panic("no return value specified for Reset")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Metrics) error); ok {
		r0 = returnFunc(context1, metrics)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMetricsRepository_Reset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reset'
type MockMetricsRepository_Reset_Call struct {
	*mock.Call
}

// Reset is a helper method to define mock.On call
//   - context1 context.Context
//   - metrics models.Metrics
func (_e *MockMetricsRepository_Expecter) Reset(context1 interface{}, metrics interface{}) *MockMetricsRepository_Reset_Call {
	return &MockMetricsRepository_Reset_Call{Call: _e.mock.On("Reset", context1, metrics)}
}

func (_c *MockMetricsRepository_Reset_Call) Run(run func(context1 context.Context, metrics models.Metrics)) *MockMetricsRepository_Reset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Metrics
		if args[1] != nil {
			arg1 = args[1].(models.Metrics)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetricsRepository_Reset_Call) Return(err error) *MockMetricsRepository_Reset_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMetricsRepository_Reset_Call) RunAndReturn(run func(context1 context.Context, metrics models.Metrics) error) *MockMetricsRepository_Reset_Call {
	_c.Call.Return(run)
	return _c
}

// ResetAll provides a mock function for the type MockMetricsRepository
func (_mock *MockMetricsRepository) ResetAll(context1 context.Context, metricss []models.Metrics) error {
	ret := _mock.Called(context1, metricss)

	if len(ret) == 0 {
		panic("no return value specified for ResetAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []models.Metrics) error); ok {
		r0 = returnFunc(context1, metricss)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMetricsRepository_ResetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetAll'
type MockMetricsRepository_ResetAll_Call struct {
	*mock.Call
}

// ResetAll is a helper method to define mock.On call
//   - context1 context.Context
//   - metricss []models.Metrics
func (_e *MockMetricsRepository_Expecter) ResetAll(context1 interface{}, metricss interface{}) *MockMetricsRepository_ResetAll_Call {
	return &MockMetricsRepository_ResetAll_Call{Call: _e.mock.On("ResetAll", context1, metricss)}
}

func (_c *MockMetricsRepository_ResetAll_Call) Run(run func(context1 context.Context, metricss []models.Metrics)) *MockMetricsRepository_ResetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []models.Metrics
		if args[1] != nil {
			arg1 = args[1].([]models.Metrics)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetricsRepository_ResetAll_Call) Return(err error) *MockMetricsRepository_ResetAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMetricsRepository_ResetAll_Call) RunAndReturn(run func(context1 context.Context, metricss []models.Metrics) error) *MockMetricsRepository_ResetAll_Call {
	_c.Call.Return(run)
	return _c
}
