// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"github.com/gabkaclassic/metrics/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMetricsRepository creates a new instance of MockMetricsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetricsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetricsRepository {
	mock := &MockMetricsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMetricsRepository is an autogenerated mock type for the MetricsRepository type
type MockMetricsRepository struct {
	mock.Mock
}

type MockMetricsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetricsRepository) EXPECT() *MockMetricsRepository_Expecter {
	return &MockMetricsRepository_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type MockMetricsRepository
func (_mock *MockMetricsRepository) Add(metric models.Metrics) error {
	ret := _mock.Called(metric)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(models.Metrics) error); ok {
		r0 = returnFunc(metric)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMetricsRepository_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockMetricsRepository_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - metric models.Metrics
func (_e *MockMetricsRepository_Expecter) Add(metric interface{}) *MockMetricsRepository_Add_Call {
	return &MockMetricsRepository_Add_Call{Call: _e.mock.On("Add", metric)}
}

func (_c *MockMetricsRepository_Add_Call) Run(run func(metric models.Metrics)) *MockMetricsRepository_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.Metrics
		if args[0] != nil {
			arg0 = args[0].(models.Metrics)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetricsRepository_Add_Call) Return(err error) *MockMetricsRepository_Add_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMetricsRepository_Add_Call) RunAndReturn(run func(metric models.Metrics) error) *MockMetricsRepository_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockMetricsRepository
func (_mock *MockMetricsRepository) Get(metricID string) (*models.Metrics, error) {
	ret := _mock.Called(metricID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *models.Metrics
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*models.Metrics, error)); ok {
		return returnFunc(metricID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *models.Metrics); ok {
		r0 = returnFunc(metricID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Metrics)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(metricID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetricsRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockMetricsRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - metricID string
func (_e *MockMetricsRepository_Expecter) Get(metricID interface{}) *MockMetricsRepository_Get_Call {
	return &MockMetricsRepository_Get_Call{Call: _e.mock.On("Get", metricID)}
}

func (_c *MockMetricsRepository_Get_Call) Run(run func(metricID string)) *MockMetricsRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetricsRepository_Get_Call) Return(metrics *models.Metrics, err error) *MockMetricsRepository_Get_Call {
	_c.Call.Return(metrics, err)
	return _c
}

func (_c *MockMetricsRepository_Get_Call) RunAndReturn(run func(metricID string) (*models.Metrics, error)) *MockMetricsRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockMetricsRepository
func (_mock *MockMetricsRepository) GetAll() *map[string]any {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 *map[string]any
	if returnFunc, ok := ret.Get(0).(func() *map[string]any); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*map[string]any)
		}
	}
	return r0
}

// MockMetricsRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockMetricsRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *MockMetricsRepository_Expecter) GetAll() *MockMetricsRepository_GetAll_Call {
	return &MockMetricsRepository_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *MockMetricsRepository_GetAll_Call) Run(run func()) *MockMetricsRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMetricsRepository_GetAll_Call) Return(stringToV *map[string]any) *MockMetricsRepository_GetAll_Call {
	_c.Call.Return(stringToV)
	return _c
}

func (_c *MockMetricsRepository_GetAll_Call) RunAndReturn(run func() *map[string]any) *MockMetricsRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// Reset provides a mock function for the type MockMetricsRepository
func (_mock *MockMetricsRepository) Reset(metric models.Metrics) error {
	ret := _mock.Called(metric)

	if len(ret) == 0 {
		panic("no return value specified for Reset")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(models.Metrics) error); ok {
		r0 = returnFunc(metric)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMetricsRepository_Reset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reset'
type MockMetricsRepository_Reset_Call struct {
	*mock.Call
}

// Reset is a helper method to define mock.On call
//   - metric models.Metrics
func (_e *MockMetricsRepository_Expecter) Reset(metric interface{}) *MockMetricsRepository_Reset_Call {
	return &MockMetricsRepository_Reset_Call{Call: _e.mock.On("Reset", metric)}
}

func (_c *MockMetricsRepository_Reset_Call) Run(run func(metric models.Metrics)) *MockMetricsRepository_Reset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.Metrics
		if args[0] != nil {
			arg0 = args[0].(models.Metrics)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetricsRepository_Reset_Call) Return(err error) *MockMetricsRepository_Reset_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMetricsRepository_Reset_Call) RunAndReturn(run func(metric models.Metrics) error) *MockMetricsRepository_Reset_Call {
	_c.Call.Return(run)
	return _c
}
