// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package httpclient

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockHTTPClient creates a new instance of MockHTTPClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHTTPClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHTTPClient {
	mock := &MockHTTPClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHTTPClient is an autogenerated mock type for the HTTPClient type
type MockHTTPClient struct {
	mock.Mock
}

type MockHTTPClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHTTPClient) EXPECT() *MockHTTPClient_Expecter {
	return &MockHTTPClient_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockHTTPClient
func (_mock *MockHTTPClient) Delete(url string, opts *RequestOptions) (*http.Response, error) {
	ret := _mock.Called(url, opts)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *http.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, *RequestOptions) (*http.Response, error)); ok {
		return returnFunc(url, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *RequestOptions) *http.Response); ok {
		r0 = returnFunc(url, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, *RequestOptions) error); ok {
		r1 = returnFunc(url, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHTTPClient_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockHTTPClient_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - url string
//   - opts *RequestOptions
func (_e *MockHTTPClient_Expecter) Delete(url interface{}, opts interface{}) *MockHTTPClient_Delete_Call {
	return &MockHTTPClient_Delete_Call{Call: _e.mock.On("Delete", url, opts)}
}

func (_c *MockHTTPClient_Delete_Call) Run(run func(url string, opts *RequestOptions)) *MockHTTPClient_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *RequestOptions
		if args[1] != nil {
			arg1 = args[1].(*RequestOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHTTPClient_Delete_Call) Return(response *http.Response, err error) *MockHTTPClient_Delete_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockHTTPClient_Delete_Call) RunAndReturn(run func(url string, opts *RequestOptions) (*http.Response, error)) *MockHTTPClient_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockHTTPClient
func (_mock *MockHTTPClient) Get(url string, opts *RequestOptions) (*http.Response, error) {
	ret := _mock.Called(url, opts)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *http.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, *RequestOptions) (*http.Response, error)); ok {
		return returnFunc(url, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *RequestOptions) *http.Response); ok {
		r0 = returnFunc(url, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, *RequestOptions) error); ok {
		r1 = returnFunc(url, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHTTPClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockHTTPClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - url string
//   - opts *RequestOptions
func (_e *MockHTTPClient_Expecter) Get(url interface{}, opts interface{}) *MockHTTPClient_Get_Call {
	return &MockHTTPClient_Get_Call{Call: _e.mock.On("Get", url, opts)}
}

func (_c *MockHTTPClient_Get_Call) Run(run func(url string, opts *RequestOptions)) *MockHTTPClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *RequestOptions
		if args[1] != nil {
			arg1 = args[1].(*RequestOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHTTPClient_Get_Call) Return(response *http.Response, err error) *MockHTTPClient_Get_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockHTTPClient_Get_Call) RunAndReturn(run func(url string, opts *RequestOptions) (*http.Response, error)) *MockHTTPClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Patch provides a mock function for the type MockHTTPClient
func (_mock *MockHTTPClient) Patch(url string, opts *RequestOptions) (*http.Response, error) {
	ret := _mock.Called(url, opts)

	if len(ret) == 0 {
		panic("no return value specified for Patch")
	}

	var r0 *http.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, *RequestOptions) (*http.Response, error)); ok {
		return returnFunc(url, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *RequestOptions) *http.Response); ok {
		r0 = returnFunc(url, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, *RequestOptions) error); ok {
		r1 = returnFunc(url, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHTTPClient_Patch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Patch'
type MockHTTPClient_Patch_Call struct {
	*mock.Call
}

// Patch is a helper method to define mock.On call
//   - url string
//   - opts *RequestOptions
func (_e *MockHTTPClient_Expecter) Patch(url interface{}, opts interface{}) *MockHTTPClient_Patch_Call {
	return &MockHTTPClient_Patch_Call{Call: _e.mock.On("Patch", url, opts)}
}

func (_c *MockHTTPClient_Patch_Call) Run(run func(url string, opts *RequestOptions)) *MockHTTPClient_Patch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *RequestOptions
		if args[1] != nil {
			arg1 = args[1].(*RequestOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHTTPClient_Patch_Call) Return(response *http.Response, err error) *MockHTTPClient_Patch_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockHTTPClient_Patch_Call) RunAndReturn(run func(url string, opts *RequestOptions) (*http.Response, error)) *MockHTTPClient_Patch_Call {
	_c.Call.Return(run)
	return _c
}

// Post provides a mock function for the type MockHTTPClient
func (_mock *MockHTTPClient) Post(url string, opts *RequestOptions) (*http.Response, error) {
	ret := _mock.Called(url, opts)

	if len(ret) == 0 {
		panic("no return value specified for Post")
	}

	var r0 *http.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, *RequestOptions) (*http.Response, error)); ok {
		return returnFunc(url, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *RequestOptions) *http.Response); ok {
		r0 = returnFunc(url, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, *RequestOptions) error); ok {
		r1 = returnFunc(url, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHTTPClient_Post_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Post'
type MockHTTPClient_Post_Call struct {
	*mock.Call
}

// Post is a helper method to define mock.On call
//   - url string
//   - opts *RequestOptions
func (_e *MockHTTPClient_Expecter) Post(url interface{}, opts interface{}) *MockHTTPClient_Post_Call {
	return &MockHTTPClient_Post_Call{Call: _e.mock.On("Post", url, opts)}
}

func (_c *MockHTTPClient_Post_Call) Run(run func(url string, opts *RequestOptions)) *MockHTTPClient_Post_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *RequestOptions
		if args[1] != nil {
			arg1 = args[1].(*RequestOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHTTPClient_Post_Call) Return(response *http.Response, err error) *MockHTTPClient_Post_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockHTTPClient_Post_Call) RunAndReturn(run func(url string, opts *RequestOptions) (*http.Response, error)) *MockHTTPClient_Post_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function for the type MockHTTPClient
func (_mock *MockHTTPClient) Put(url string, opts *RequestOptions) (*http.Response, error) {
	ret := _mock.Called(url, opts)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 *http.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, *RequestOptions) (*http.Response, error)); ok {
		return returnFunc(url, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *RequestOptions) *http.Response); ok {
		r0 = returnFunc(url, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, *RequestOptions) error); ok {
		r1 = returnFunc(url, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHTTPClient_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockHTTPClient_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - url string
//   - opts *RequestOptions
func (_e *MockHTTPClient_Expecter) Put(url interface{}, opts interface{}) *MockHTTPClient_Put_Call {
	return &MockHTTPClient_Put_Call{Call: _e.mock.On("Put", url, opts)}
}

func (_c *MockHTTPClient_Put_Call) Run(run func(url string, opts *RequestOptions)) *MockHTTPClient_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *RequestOptions
		if args[1] != nil {
			arg1 = args[1].(*RequestOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHTTPClient_Put_Call) Return(response *http.Response, err error) *MockHTTPClient_Put_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockHTTPClient_Put_Call) RunAndReturn(run func(url string, opts *RequestOptions) (*http.Response, error)) *MockHTTPClient_Put_Call {
	_c.Call.Return(run)
	return _c
}
