// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package audit

import (
	models "github.com/gabkaclassic/metrics/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// newMockhandler creates a new instance of mockhandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockhandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockhandler {
	mock := &mockhandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockhandler is an autogenerated mock type for the handler type
type mockhandler struct {
	mock.Mock
}

type mockhandler_Expecter struct {
	mock *mock.Mock
}

func (_m *mockhandler) EXPECT() *mockhandler_Expecter {
	return &mockhandler_Expecter{mock: &_m.Mock}
}

// handle provides a mock function for the type mockhandler
func (_mock *mockhandler) handle(eventMoqParam event) {
	_mock.Called(eventMoqParam)
	return
}

// mockhandler_handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'handle'
type mockhandler_handle_Call struct {
	*mock.Call
}

// handle is a helper method to define mock.On call
//   - eventMoqParam event
func (_e *mockhandler_Expecter) handle(eventMoqParam interface{}) *mockhandler_handle_Call {
	return &mockhandler_handle_Call{Call: _e.mock.On("handle", eventMoqParam)}
}

func (_c *mockhandler_handle_Call) Run(run func(eventMoqParam event)) *mockhandler_handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 event
		if args[0] != nil {
			arg0 = args[0].(event)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockhandler_handle_Call) Return() *mockhandler_handle_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockhandler_handle_Call) RunAndReturn(run func(eventMoqParam event)) *mockhandler_handle_Call {
	_c.Run(run)
	return _c
}

// NewMockAuditor creates a new instance of MockAuditor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuditor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuditor {
	mock := &MockAuditor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuditor is an autogenerated mock type for the Auditor type
type MockAuditor struct {
	mock.Mock
}

type MockAuditor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuditor) EXPECT() *MockAuditor_Expecter {
	return &MockAuditor_Expecter{mock: &_m.Mock}
}

// AuditMany provides a mock function for the type MockAuditor
func (_mock *MockAuditor) AuditMany(metricss []models.Metrics, n int64, s string) {
	_mock.Called(metricss, n, s)
	return
}

// MockAuditor_AuditMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuditMany'
type MockAuditor_AuditMany_Call struct {
	*mock.Call
}

// AuditMany is a helper method to define mock.On call
//   - metricss []models.Metrics
//   - n int64
//   - s string
func (_e *MockAuditor_Expecter) AuditMany(metricss interface{}, n interface{}, s interface{}) *MockAuditor_AuditMany_Call {
	return &MockAuditor_AuditMany_Call{Call: _e.mock.On("AuditMany", metricss, n, s)}
}

func (_c *MockAuditor_AuditMany_Call) Run(run func(metricss []models.Metrics, n int64, s string)) *MockAuditor_AuditMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []models.Metrics
		if args[0] != nil {
			arg0 = args[0].([]models.Metrics)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuditor_AuditMany_Call) Return() *MockAuditor_AuditMany_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAuditor_AuditMany_Call) RunAndReturn(run func(metricss []models.Metrics, n int64, s string)) *MockAuditor_AuditMany_Call {
	_c.Run(run)
	return _c
}

// AuditOne provides a mock function for the type MockAuditor
func (_mock *MockAuditor) AuditOne(metrics models.Metrics, n int64, s string) {
	_mock.Called(metrics, n, s)
	return
}

// MockAuditor_AuditOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuditOne'
type MockAuditor_AuditOne_Call struct {
	*mock.Call
}

// AuditOne is a helper method to define mock.On call
//   - metrics models.Metrics
//   - n int64
//   - s string
func (_e *MockAuditor_Expecter) AuditOne(metrics interface{}, n interface{}, s interface{}) *MockAuditor_AuditOne_Call {
	return &MockAuditor_AuditOne_Call{Call: _e.mock.On("AuditOne", metrics, n, s)}
}

func (_c *MockAuditor_AuditOne_Call) Run(run func(metrics models.Metrics, n int64, s string)) *MockAuditor_AuditOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.Metrics
		if args[0] != nil {
			arg0 = args[0].(models.Metrics)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuditor_AuditOne_Call) Return() *MockAuditor_AuditOne_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAuditor_AuditOne_Call) RunAndReturn(run func(metrics models.Metrics, n int64, s string)) *MockAuditor_AuditOne_Call {
	_c.Run(run)
	return _c
}
