// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	models "github.com/gabkaclassic/metrics/internal/model"
	api "github.com/gabkaclassic/metrics/pkg/error"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMetricsService creates a new instance of MockMetricsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetricsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetricsService {
	mock := &MockMetricsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMetricsService is an autogenerated mock type for the MetricsService type
type MockMetricsService struct {
	mock.Mock
}

type MockMetricsService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetricsService) EXPECT() *MockMetricsService_Expecter {
	return &MockMetricsService_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockMetricsService
func (_mock *MockMetricsService) Get(context1 context.Context, s string, s1 string) (any, *api.APIError) {
	ret := _mock.Called(context1, s, s1)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 any
	var r1 *api.APIError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (any, *api.APIError)); ok {
		return returnFunc(context1, s, s1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) any); ok {
		r0 = returnFunc(context1, s, s1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) *api.APIError); ok {
		r1 = returnFunc(context1, s, s1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*api.APIError)
		}
	}
	return r0, r1
}

// MockMetricsService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockMetricsService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
func (_e *MockMetricsService_Expecter) Get(context1 interface{}, s interface{}, s1 interface{}) *MockMetricsService_Get_Call {
	return &MockMetricsService_Get_Call{Call: _e.mock.On("Get", context1, s, s1)}
}

func (_c *MockMetricsService_Get_Call) Run(run func(context1 context.Context, s string, s1 string)) *MockMetricsService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMetricsService_Get_Call) Return(v any, aPIError *api.APIError) *MockMetricsService_Get_Call {
	_c.Call.Return(v, aPIError)
	return _c
}

func (_c *MockMetricsService_Get_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string) (any, *api.APIError)) *MockMetricsService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockMetricsService
func (_mock *MockMetricsService) GetAll(context1 context.Context) (map[string]any, *api.APIError) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 map[string]any
	var r1 *api.APIError
	if returnFunc, ok := ret.Get(0).(func(context.Context) (map[string]any, *api.APIError)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) map[string]any); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) *api.APIError); ok {
		r1 = returnFunc(context1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*api.APIError)
		}
	}
	return r0, r1
}

// MockMetricsService_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockMetricsService_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockMetricsService_Expecter) GetAll(context1 interface{}) *MockMetricsService_GetAll_Call {
	return &MockMetricsService_GetAll_Call{Call: _e.mock.On("GetAll", context1)}
}

func (_c *MockMetricsService_GetAll_Call) Run(run func(context1 context.Context)) *MockMetricsService_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetricsService_GetAll_Call) Return(stringToV map[string]any, aPIError *api.APIError) *MockMetricsService_GetAll_Call {
	_c.Call.Return(stringToV, aPIError)
	return _c
}

func (_c *MockMetricsService_GetAll_Call) RunAndReturn(run func(context1 context.Context) (map[string]any, *api.APIError)) *MockMetricsService_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetStruct provides a mock function for the type MockMetricsService
func (_mock *MockMetricsService) GetStruct(context1 context.Context, s string, s1 string) (models.Metrics, *api.APIError) {
	ret := _mock.Called(context1, s, s1)

	if len(ret) == 0 {
		panic("no return value specified for GetStruct")
	}

	var r0 models.Metrics
	var r1 *api.APIError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (models.Metrics, *api.APIError)); ok {
		return returnFunc(context1, s, s1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) models.Metrics); ok {
		r0 = returnFunc(context1, s, s1)
	} else {
		r0 = ret.Get(0).(models.Metrics)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) *api.APIError); ok {
		r1 = returnFunc(context1, s, s1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*api.APIError)
		}
	}
	return r0, r1
}

// MockMetricsService_GetStruct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStruct'
type MockMetricsService_GetStruct_Call struct {
	*mock.Call
}

// GetStruct is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
func (_e *MockMetricsService_Expecter) GetStruct(context1 interface{}, s interface{}, s1 interface{}) *MockMetricsService_GetStruct_Call {
	return &MockMetricsService_GetStruct_Call{Call: _e.mock.On("GetStruct", context1, s, s1)}
}

func (_c *MockMetricsService_GetStruct_Call) Run(run func(context1 context.Context, s string, s1 string)) *MockMetricsService_GetStruct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMetricsService_GetStruct_Call) Return(metrics models.Metrics, aPIError *api.APIError) *MockMetricsService_GetStruct_Call {
	_c.Call.Return(metrics, aPIError)
	return _c
}

func (_c *MockMetricsService_GetStruct_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string) (models.Metrics, *api.APIError)) *MockMetricsService_GetStruct_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockMetricsService
func (_mock *MockMetricsService) Save(context1 context.Context, s string, s1 string, s2 string) *api.APIError {
	ret := _mock.Called(context1, s, s1, s2)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *api.APIError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *api.APIError); ok {
		r0 = returnFunc(context1, s, s1, s2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.APIError)
		}
	}
	return r0
}

// MockMetricsService_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockMetricsService_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - s2 string
func (_e *MockMetricsService_Expecter) Save(context1 interface{}, s interface{}, s1 interface{}, s2 interface{}) *MockMetricsService_Save_Call {
	return &MockMetricsService_Save_Call{Call: _e.mock.On("Save", context1, s, s1, s2)}
}

func (_c *MockMetricsService_Save_Call) Run(run func(context1 context.Context, s string, s1 string, s2 string)) *MockMetricsService_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockMetricsService_Save_Call) Return(aPIError *api.APIError) *MockMetricsService_Save_Call {
	_c.Call.Return(aPIError)
	return _c
}

func (_c *MockMetricsService_Save_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, s2 string) *api.APIError) *MockMetricsService_Save_Call {
	_c.Call.Return(run)
	return _c
}

// SaveAll provides a mock function for the type MockMetricsService
func (_mock *MockMetricsService) SaveAll(context1 context.Context, metricss []models.Metrics) *api.APIError {
	ret := _mock.Called(context1, metricss)

	if len(ret) == 0 {
		panic("no return value specified for SaveAll")
	}

	var r0 *api.APIError
	if returnFunc, ok := ret.Get(0).(func(context.Context, []models.Metrics) *api.APIError); ok {
		r0 = returnFunc(context1, metricss)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.APIError)
		}
	}
	return r0
}

// MockMetricsService_SaveAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveAll'
type MockMetricsService_SaveAll_Call struct {
	*mock.Call
}

// SaveAll is a helper method to define mock.On call
//   - context1 context.Context
//   - metricss []models.Metrics
func (_e *MockMetricsService_Expecter) SaveAll(context1 interface{}, metricss interface{}) *MockMetricsService_SaveAll_Call {
	return &MockMetricsService_SaveAll_Call{Call: _e.mock.On("SaveAll", context1, metricss)}
}

func (_c *MockMetricsService_SaveAll_Call) Run(run func(context1 context.Context, metricss []models.Metrics)) *MockMetricsService_SaveAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []models.Metrics
		if args[1] != nil {
			arg1 = args[1].([]models.Metrics)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetricsService_SaveAll_Call) Return(aPIError *api.APIError) *MockMetricsService_SaveAll_Call {
	_c.Call.Return(aPIError)
	return _c
}

func (_c *MockMetricsService_SaveAll_Call) RunAndReturn(run func(context1 context.Context, metricss []models.Metrics) *api.APIError) *MockMetricsService_SaveAll_Call {
	_c.Call.Return(run)
	return _c
}

// SaveStruct provides a mock function for the type MockMetricsService
func (_mock *MockMetricsService) SaveStruct(context1 context.Context, metrics models.Metrics) *api.APIError {
	ret := _mock.Called(context1, metrics)

	if len(ret) == 0 {
		panic("no return value specified for SaveStruct")
	}

	var r0 *api.APIError
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Metrics) *api.APIError); ok {
		r0 = returnFunc(context1, metrics)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.APIError)
		}
	}
	return r0
}

// MockMetricsService_SaveStruct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveStruct'
type MockMetricsService_SaveStruct_Call struct {
	*mock.Call
}

// SaveStruct is a helper method to define mock.On call
//   - context1 context.Context
//   - metrics models.Metrics
func (_e *MockMetricsService_Expecter) SaveStruct(context1 interface{}, metrics interface{}) *MockMetricsService_SaveStruct_Call {
	return &MockMetricsService_SaveStruct_Call{Call: _e.mock.On("SaveStruct", context1, metrics)}
}

func (_c *MockMetricsService_SaveStruct_Call) Run(run func(context1 context.Context, metrics models.Metrics)) *MockMetricsService_SaveStruct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Metrics
		if args[1] != nil {
			arg1 = args[1].(models.Metrics)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetricsService_SaveStruct_Call) Return(aPIError *api.APIError) *MockMetricsService_SaveStruct_Call {
	_c.Call.Return(aPIError)
	return _c
}

func (_c *MockMetricsService_SaveStruct_Call) RunAndReturn(run func(context1 context.Context, metrics models.Metrics) *api.APIError) *MockMetricsService_SaveStruct_Call {
	_c.Call.Return(run)
	return _c
}
