// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package hash

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockSigner creates a new instance of MockSigner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSigner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSigner {
	mock := &MockSigner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSigner is an autogenerated mock type for the Signer type
type MockSigner struct {
	mock.Mock
}

type MockSigner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSigner) EXPECT() *MockSigner_Expecter {
	return &MockSigner_Expecter{mock: &_m.Mock}
}

// Sign provides a mock function for the type MockSigner
func (_mock *MockSigner) Sign(data []byte) string {
	ret := _mock.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for Sign")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func([]byte) string); ok {
		r0 = returnFunc(data)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockSigner_Sign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sign'
type MockSigner_Sign_Call struct {
	*mock.Call
}

// Sign is a helper method to define mock.On call
//   - data []byte
func (_e *MockSigner_Expecter) Sign(data interface{}) *MockSigner_Sign_Call {
	return &MockSigner_Sign_Call{Call: _e.mock.On("Sign", data)}
}

func (_c *MockSigner_Sign_Call) Run(run func(data []byte)) *MockSigner_Sign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSigner_Sign_Call) Return(s string) *MockSigner_Sign_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockSigner_Sign_Call) RunAndReturn(run func(data []byte) string) *MockSigner_Sign_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVerifier creates a new instance of MockVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVerifier {
	mock := &MockVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVerifier is an autogenerated mock type for the Verifier type
type MockVerifier struct {
	mock.Mock
}

type MockVerifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVerifier) EXPECT() *MockVerifier_Expecter {
	return &MockVerifier_Expecter{mock: &_m.Mock}
}

// Verify provides a mock function for the type MockVerifier
func (_mock *MockVerifier) Verify(data []byte, sign string) bool {
	ret := _mock.Called(data, sign)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func([]byte, string) bool); ok {
		r0 = returnFunc(data, sign)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockVerifier_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockVerifier_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - data []byte
//   - sign string
func (_e *MockVerifier_Expecter) Verify(data interface{}, sign interface{}) *MockVerifier_Verify_Call {
	return &MockVerifier_Verify_Call{Call: _e.mock.On("Verify", data, sign)}
}

func (_c *MockVerifier_Verify_Call) Run(run func(data []byte, sign string)) *MockVerifier_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVerifier_Verify_Call) Return(b bool) *MockVerifier_Verify_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockVerifier_Verify_Call) RunAndReturn(run func(data []byte, sign string) bool) *MockVerifier_Verify_Call {
	_c.Call.Return(run)
	return _c
}
