// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package metric

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockGauge creates a new instance of MockGauge. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGauge(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGauge {
	mock := &MockGauge{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGauge is an autogenerated mock type for the Gauge type
type MockGauge struct {
	mock.Mock
}

type MockGauge_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGauge) EXPECT() *MockGauge_Expecter {
	return &MockGauge_Expecter{mock: &_m.Mock}
}

// Name provides a mock function for the type MockGauge
func (_mock *MockGauge) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockGauge_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockGauge_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockGauge_Expecter) Name() *MockGauge_Name_Call {
	return &MockGauge_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockGauge_Name_Call) Run(run func()) *MockGauge_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGauge_Name_Call) Return(s string) *MockGauge_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockGauge_Name_Call) RunAndReturn(run func() string) *MockGauge_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Type provides a mock function for the type MockGauge
func (_mock *MockGauge) Type() MetricType {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 MetricType
	if returnFunc, ok := ret.Get(0).(func() MetricType); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(MetricType)
	}
	return r0
}

// MockGauge_Type_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Type'
type MockGauge_Type_Call struct {
	*mock.Call
}

// Type is a helper method to define mock.On call
func (_e *MockGauge_Expecter) Type() *MockGauge_Type_Call {
	return &MockGauge_Type_Call{Call: _e.mock.On("Type")}
}

func (_c *MockGauge_Type_Call) Run(run func()) *MockGauge_Type_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGauge_Type_Call) Return(metricType MetricType) *MockGauge_Type_Call {
	_c.Call.Return(metricType)
	return _c
}

func (_c *MockGauge_Type_Call) RunAndReturn(run func() MetricType) *MockGauge_Type_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockGauge
func (_mock *MockGauge) Update() {
	_mock.Called()
	return
}

// MockGauge_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockGauge_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
func (_e *MockGauge_Expecter) Update() *MockGauge_Update_Call {
	return &MockGauge_Update_Call{Call: _e.mock.On("Update")}
}

func (_c *MockGauge_Update_Call) Run(run func()) *MockGauge_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGauge_Update_Call) Return() *MockGauge_Update_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockGauge_Update_Call) RunAndReturn(run func()) *MockGauge_Update_Call {
	_c.Run(run)
	return _c
}

// Value provides a mock function for the type MockGauge
func (_mock *MockGauge) Value() any {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Value")
	}

	var r0 any
	if returnFunc, ok := ret.Get(0).(func() any); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	return r0
}

// MockGauge_Value_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Value'
type MockGauge_Value_Call struct {
	*mock.Call
}

// Value is a helper method to define mock.On call
func (_e *MockGauge_Expecter) Value() *MockGauge_Value_Call {
	return &MockGauge_Value_Call{Call: _e.mock.On("Value")}
}

func (_c *MockGauge_Value_Call) Run(run func()) *MockGauge_Value_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGauge_Value_Call) Return(v any) *MockGauge_Value_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockGauge_Value_Call) RunAndReturn(run func() any) *MockGauge_Value_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMetric creates a new instance of MockMetric. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetric(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetric {
	mock := &MockMetric{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMetric is an autogenerated mock type for the Metric type
type MockMetric struct {
	mock.Mock
}

type MockMetric_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetric) EXPECT() *MockMetric_Expecter {
	return &MockMetric_Expecter{mock: &_m.Mock}
}

// Name provides a mock function for the type MockMetric
func (_mock *MockMetric) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockMetric_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockMetric_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockMetric_Expecter) Name() *MockMetric_Name_Call {
	return &MockMetric_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockMetric_Name_Call) Run(run func()) *MockMetric_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMetric_Name_Call) Return(s string) *MockMetric_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockMetric_Name_Call) RunAndReturn(run func() string) *MockMetric_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Type provides a mock function for the type MockMetric
func (_mock *MockMetric) Type() MetricType {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 MetricType
	if returnFunc, ok := ret.Get(0).(func() MetricType); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(MetricType)
	}
	return r0
}

// MockMetric_Type_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Type'
type MockMetric_Type_Call struct {
	*mock.Call
}

// Type is a helper method to define mock.On call
func (_e *MockMetric_Expecter) Type() *MockMetric_Type_Call {
	return &MockMetric_Type_Call{Call: _e.mock.On("Type")}
}

func (_c *MockMetric_Type_Call) Run(run func()) *MockMetric_Type_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMetric_Type_Call) Return(metricType MetricType) *MockMetric_Type_Call {
	_c.Call.Return(metricType)
	return _c
}

func (_c *MockMetric_Type_Call) RunAndReturn(run func() MetricType) *MockMetric_Type_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockMetric
func (_mock *MockMetric) Update() {
	_mock.Called()
	return
}

// MockMetric_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockMetric_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
func (_e *MockMetric_Expecter) Update() *MockMetric_Update_Call {
	return &MockMetric_Update_Call{Call: _e.mock.On("Update")}
}

func (_c *MockMetric_Update_Call) Run(run func()) *MockMetric_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMetric_Update_Call) Return() *MockMetric_Update_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMetric_Update_Call) RunAndReturn(run func()) *MockMetric_Update_Call {
	_c.Run(run)
	return _c
}

// Value provides a mock function for the type MockMetric
func (_mock *MockMetric) Value() any {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Value")
	}

	var r0 any
	if returnFunc, ok := ret.Get(0).(func() any); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	return r0
}

// MockMetric_Value_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Value'
type MockMetric_Value_Call struct {
	*mock.Call
}

// Value is a helper method to define mock.On call
func (_e *MockMetric_Expecter) Value() *MockMetric_Value_Call {
	return &MockMetric_Value_Call{Call: _e.mock.On("Value")}
}

func (_c *MockMetric_Value_Call) Run(run func()) *MockMetric_Value_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMetric_Value_Call) Return(v any) *MockMetric_Value_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockMetric_Value_Call) RunAndReturn(run func() any) *MockMetric_Value_Call {
	_c.Call.Return(run)
	return _c
}
